Analyse des signaux médicaux - Séance 1 de TP
--

At the end of this session, you will be able to : 
- Create and manage the Jupyter Notebooks environment to run code, insert text and math equations
- Perform basic matrix manipulations using Numpy 
- Create signals and perform basic scientific computing using Scipy and Numpy
- Produce simple data visulisation using Matplotlib 
- Open, manipulate and visualize an EEG dataset used in the course

Part 1 - Intro to Jupyter Notebook
--
Here, we will only cover the basics. 

Jupyter Notebook is based on the .ipynb format (iPython Notebook), and is essentially a way to do rapid prototyping / demonstrations of scientific python. The basic idea is to define *cells*. 
Cellss can be of several types, including python code, or rich text (using [markdown formatting](https://www.markdownguide.org/basic-syntax/)).

When a code cell is evaluated (i.e. the python code will be executed), the output of this evaluation will show up right below the cell. 

When a text cell is evaluated, the text will be formatted. 

You can now do the "User Interface Tour" from the Help menu. 

Done ? 

When working with Jupyter Notebook, you will essentially switch between two modes : 
- The Edit mode in which you edit the content of the cells 
- The Command mode, that enables you to change the cell types. 

When in Command mode, you can select cells. If you select a single cell, you can edit it by simply pressing enter, or double clicking on it. 

For example, try editing THIS CELL and change its content. 

Now, edit the cell below, change the code, and when you're done, press Shift+Enter to evalute the code. 

In [1]:
### CELL TO BE EDITED

a=32
b= 2*a
print("%d + %d"%(a,b))

32 + 64


Text cells can contain math expressions that use the Markdown formatting, in which you can use LaTEx expressions for maths (enclosed between two dollar signs). 

For example : $A(k) \triangleq \sum_{\mathbf{n} =1}^{k}{n^2}$

Now : 
- Edit the current cell to show the code that displays the math expression,
- Create a code cell below that defines a function that calculates $A(k)$ given k, and evaluate this cell,
- Create another cell and use the function to display $A(k)$ for a few values of $\mathbf{k}$ (eg 10 and 20).

In [2]:
### CELL TO BE COMPLETED 

def A(k):
    result = 1
    ###  your code here
    return result

In [3]:
### CELL TO BE COMPLETED 
###  your code here

Note that using Jupyter Notebook, if you evaluate a cell with a function followed by a "?" sign, the help of the function will pop up. 

Example : 

In [4]:
import os

os.listdir?

You can also display the code of a function using the syntax "??" 

In [5]:
A??

The popup can be closed by pressing the Escape key. 

Use the listdir function to browse the content of some directories... 


In [6]:
os.listdir('../')

['TP', 'README.md', '.git', 'LICENSE', 'ExG_course_slides.pdf']

In [7]:
os.listdir('./')

['README.md', 'SignauxMedicauxTP1.ipynb', '.ipynb_checkpoints']

Part 2 - Introduction to Numpy, Scipy and Matplotlib 
--

A code cell can contain any python code, including imports. Let's start by importing the Numpy package. 

In [8]:
import numpy as np

Numpy can be used to generate pseudo-random values from various distributions. In particular, a very useful distribution is the standard normal (zero mean and unit variance). Let's generate two vectors sampled from the normal distribution, using a length parameter that we'll be able to change if needed. 

In [9]:
length = 50

vecA = np.random.randn(length)
vecB = np.random.randn(2*length)

vecA and vecB are numpy *arrays*. One of their attributes can be fetched to check their *shape*

In [10]:
print(vecA.shape)
print(vecB.shape)

(50,)
(100,)


In [11]:
print(vecA)

[ 1.15342001  0.26273588  0.37540782 -0.98605866 -0.64187501  0.25283736
  0.28486771 -0.56363029 -0.08943265 -0.01785777 -0.71325248 -0.43235139
  1.13170387  0.53597515  1.47295824  1.46025194  0.85138616  1.68646175
  0.17703236 -0.93363455 -0.73282676  1.55392423  0.51274898  0.12355134
 -1.12947079 -0.76809347 -0.0584957   0.17512692  0.58802852 -0.47811578
  0.03504814 -1.27123657 -1.33662539  0.38870321 -0.33573976 -1.15902538
 -0.45390921  0.13807248  0.71333922  1.11722513 -1.11713147 -0.23517463
 -0.1905481   0.88553643 -0.43380445 -0.32816125  0.87033665  0.18722732
 -1.41811019 -0.52315199]


Numpy arrays can be vectors as well as matrices, or any tensor. For example the following code will create tensors with 3 dimensions using the standard normal

This could be used for instance for EEG signals in the time frequency domain. Let's imagine we have Power Spectral Density in 10 frequency bands, 1 second at 500 Hz, and 5 electrodes. We can generate a random signal with such shape by using numpy random generators.

Check the syntax of the np.random.randn function, and generate an array called EEG_timefreq, with the specifications  (10 frequency bands, 1 second at 500 Hz, and 5 electrodes)

In [12]:
### EEG_timefreq =  ## TO BE COMPLETED
EEG_timefreq = np.random.randn(10,500,5)
print(EEG_timefreq.shape)

(10, 500, 5)


Note that the random package of Numpy has several other interesting functions. Try to test the two functions proposed in the cell below. 

Try uncommenting the two functions below one by one, look up their help page, and try to use them. 

In [13]:
### CELL TO BE COMPLETED 

#np.random.randint
#np.random.permutation

A very important features of arrays is the fact they can be used as *iterables*. For example, you can iterate over the dimensions of an array by simply "looping" over it using a *for* loop

In [14]:
for freqband in EEG_timefreq:
    print(freqband.shape)

(500, 5)
(500, 5)
(500, 5)
(500, 5)
(500, 5)
(500, 5)
(500, 5)
(500, 5)
(500, 5)
(500, 5)


This way, we can loop over frequency bands, and process each frequency band separately. 

Also possible to enumerate along the dimension in order to get the index of the current "smaller" array


In [15]:
print('Initial shape is %d %d %d' % (EEG_timefreq.shape[0],EEG_timefreq.shape[1],EEG_timefreq.shape[2]))
print('Iterating over the first dimension using an index k')
for k,curdim in enumerate(EEG_timefreq):
    print('k = %d, shape is %d %d' % (k,curdim.shape[0],curdim.shape[1]))

Initial shape is 10 500 5
Iterating over the first dimension using an index k
k = 0, shape is 500 5
k = 1, shape is 500 5
k = 2, shape is 500 5
k = 3, shape is 500 5
k = 4, shape is 500 5
k = 5, shape is 500 5
k = 6, shape is 500 5
k = 7, shape is 500 5
k = 8, shape is 500 5
k = 9, shape is 500 5


Now let's imagine we want to calculate the average power over time and electrode, for each couple frequency band. 

Use the previous principle in order to calculate the average of each frequency band subvector, using the function np.mean()

In [16]:
### CELL TO BE COMPLETED 

for k,curdim in enumerate(EEG_timefreq):
    print(np.mean(curdim))

0.03006740190677612
-0.044625980900991284
0.038933511085920296
0.02490202977780868
-0.010965825708711234
-0.005386643081759948
-0.008085152967445944
-0.022960642137006316
-0.00465748007887781
-0.002414310968749581


Check that you obtain the same result when directly computing the average over the two axis 1 and 2 (look up the arguments of np.mean), which correspond to averaging in time and electrode.

In [17]:
### CELL TO BE COMPLETED 

np.mean(EEG_timefreq,axis = (1,2))

array([ 0.0300674 , -0.04462598,  0.03893351,  0.02490203, -0.01096583,
       -0.00538664, -0.00808515, -0.02296064, -0.00465748, -0.00241431])

These features will prove to be very useful when manipulate large arrays. 

Another important operation when working with Numpy Arrays is *reshaping*. Essentially, *reshaping* consists in changing the organisation of the array (in terms of dimension), while keeping the same number of elements. For example, a 20x10 2D array can be converted into a 4x5x10 array

In [18]:
A = np.random.randint(1,5,(10,20))
print('Initial shape of A is %d x %d' % (A.shape[0],A.shape[1]))
print(A)
B = A.reshape((4,5,10))
print('B is A reshaped to %d x %d x %d' % (B.shape[0],B.shape[1],B.shape[2]))
print(B)

Initial shape of A is 10 x 20
[[4 3 1 3 3 1 3 1 4 4 2 4 1 2 1 3 2 2 3 3]
 [3 1 1 1 1 3 4 1 1 2 3 2 2 3 4 2 4 1 4 2]
 [1 2 3 3 4 4 1 4 4 4 3 1 1 2 3 3 3 3 1 4]
 [4 2 3 2 2 2 1 1 4 2 4 1 3 1 3 2 1 1 1 4]
 [2 1 2 1 2 2 4 1 1 1 1 4 4 3 4 4 1 2 4 1]
 [2 1 2 2 3 1 2 4 1 3 1 3 4 4 1 2 2 3 1 1]
 [4 1 2 2 2 1 3 2 1 4 1 3 4 4 3 3 1 4 3 2]
 [3 3 2 1 2 4 3 1 2 1 2 4 1 3 3 4 3 2 3 4]
 [1 2 4 4 3 1 4 3 2 1 2 4 2 4 3 2 1 3 2 1]
 [3 2 1 1 2 4 1 4 3 3 4 4 1 4 4 4 4 2 1 3]]
B is A reshaped to 4 x 5 x 10
[[[4 3 1 3 3 1 3 1 4 4]
  [2 4 1 2 1 3 2 2 3 3]
  [3 1 1 1 1 3 4 1 1 2]
  [3 2 2 3 4 2 4 1 4 2]
  [1 2 3 3 4 4 1 4 4 4]]

 [[3 1 1 2 3 3 3 3 1 4]
  [4 2 3 2 2 2 1 1 4 2]
  [4 1 3 1 3 2 1 1 1 4]
  [2 1 2 1 2 2 4 1 1 1]
  [1 4 4 3 4 4 1 2 4 1]]

 [[2 1 2 2 3 1 2 4 1 3]
  [1 3 4 4 1 2 2 3 1 1]
  [4 1 2 2 2 1 3 2 1 4]
  [1 3 4 4 3 3 1 4 3 2]
  [3 3 2 1 2 4 3 1 2 1]]

 [[2 4 1 3 3 4 3 2 3 4]
  [1 2 4 4 3 1 4 3 2 1]
  [2 4 2 4 3 2 1 3 2 1]
  [3 2 1 1 2 4 1 4 3 3]
  [4 4 1 4 4 4 4 2 1 3]]]


Now try implementing the same function $A(k)$ that we implemented in part 1 using numpy.

Recall that $A(k) \triangleq \sum_{\mathbf{n} =1}^{k}{n^2}$

The following numpy auxiliary functions can help you:
   - power: (np.power(base,exponent), example: np.power(2,2) = 4
   - arange: (np.arange(last element), example: np.arange(5) = [0,1,2,3,4]
   - sum: (np.sum(vector), example: np.sum([0,1,2,3]) = 6
   
   
Use these numpy functions to calculates $A(1)$ through $A(10)$ in a single for loop.

In [19]:
### CELL TO BE COMPLETED 
for i in range(1,10):
    a = np.sum(np.power(np.arange(i),2))+1
    print(a)

1
2
6
15
31
56
92
141
205


One property of numpy that is really important is broadcasting. The goal of broadcasting is to simplify the vectorization of certain operations when the vectors do not have the same shape. For example you can easily perform element-wise multiplication.

To test this try doing an element-wise multiplication of the vector x and matrix y below

In [20]:
x = np.array([2,3])
y = np.array([[4,1],[9,10],[12,13]])
result = x*y
print("X: ",x)
print("Y: ")
print(y)
print("X shape is: ",x.shape)
print("Y shape is: ",y.shape)
print("Element-wise multiplication shape:", result.shape)
print("Element-wise multiplication result:")
print(result)


X:  [2 3]
Y: 
[[ 4  1]
 [ 9 10]
 [12 13]]
X shape is:  (2,)
Y shape is:  (3, 2)
Element-wise multiplication shape: (3, 2)
Element-wise multiplication result:
[[ 8  3]
 [18 30]
 [24 39]]


Another very powerful tool in numpy is indexing. You can use either an integer vector or a boolean vector to choose which indexes you want to extract from your numpy tensor.

Consider that we want to extract all elements from the first line of your vector y that have a higher value than 1, you would have to do:

In [21]:
first_row = y[0]
first_row_higher_than_one = first_row > 1
print("Result: ", first_row[first_row_higher_than_one])

Result:  [4]


You can also choose specific lines to query, for example if you want to query lines 0 and 2

In [22]:
rows = [0,2]
rows_result = y[rows]
values_higher_than_one = rows_result > 1
print("Result: ", rows_result[values_higher_than_one])

Result:  [ 4 12 13]


You can also save and load your numpy tensors using np.savez and np.load. This will be really important as this enable you to generate your data only once instead of having to do all the calculations every time you need your data.

In [23]:
filename = "x.npz"
source_tensor = x
np.savez(filename,data=source_tensor)

In [24]:
loaded_npz = np.load(filename)
loaded_tensor = loaded_npz["data"]
print("Your tensor was loaded and contains: ", loaded_tensor)

Your tensor was loaded and contains:  [2 3]


Part 3 - Application to an EEG dataset
--

Let's load some EEG data acquired with OpenBCI and visualize it

In [25]:
import matplotlib.pyplot as plt
%matplotlib inline